### ISSUE TITLE
Problem Installation on Windows caused by Adafruit BBIO Compilation

### ISSUE THREAD

**Issue by rupello** [MrYsLab/xideco#4]
The package installation failed for me on Windows (the Linux Adafruit BBIO package fails to compile)

Is it intended to support Windows? I worked around the issue by downloading the source and commenting out the Adafruit package in setup.py & it got the package installed OK

**Comment by MrYsLab** [comment]
Thanks for letting me know. I have removed the adafruit package from setup.py and made a note in the wiki to manually install it if using a BeagleBone Black.

Version 0.5.2 should solve the issue.
